# Generated by Django 5.1.6 on 2025-03-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='choices',
            field=models.TextField(blank=True, help_text='JSON array of choices for choice fields (e.g., ["Red", "Green", "Blue"])'),
        ),
    ]
