# Generated by Django 5.1.6 on 2025-03-04 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_add_registration_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['-registration_date']},
        ),
    ]
