# Generated by Django 5.1.6 on 2025-03-04 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_alter_registration_options'),
        ('registrations', '0004_remove_qr_code_field'),
    ]

    operations = [
    ]
