# Generated by Django 5.1.6 on 2025-03-04 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_add_checkin_fields'),
        ('registrations', '0005_merge_20250304_0747'),
    ]

    operations = [
    ]
