# Generated by Django 5.1.6 on 2025-03-16 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0009_alter_emailcommunication_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailcommunication',
            name='user',
        ),
        migrations.AddField(
            model_name='emailcommunication',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_communications', to='registrations.registration'),
        ),
    ]
